### ISSUE TITLE
rerunning docker compose up error admin is taken

### ISSUE THREAD

**Issue by myrsk** [unmade/shelf-back#137] opened 2023-02-18 21:48 UTC
When i stop the containers, and start them again using docker compose up I get the below

```
...
 File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/src/shelf-back/app/db.py", line 74, in create_client
    yield client
  File "/usr/src/shelf-back/manage.py", line 45, in _createuser
    await actions.create_account(conn, username, password, superuser=True)
  File "/usr/src/shelf-back/app/actions.py", line 82, in create_account
    user = await crud.user.create(tx, username, password, superuser=superuser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/shelf-back/app/crud/user.py", line 97, in create
    raise errors.UserAlreadyExists(f"Username '{username}' is taken") from exc
app.errors.UserAlreadyExists: Username 'admin' is taken
```
and from the console i can see : shelf-showcase-shelf-back-1 exited with code 1

It seems that it wants to create an admin account again, and that makes the backend container exit.

Edit: I have to kill all the containers, and delete the volume and then re run docker compose up - once everything is up, I have to reindex as well ... quite cumbersome

Is there a fixed? :)

Thanks.

**Comment by unmade** [comment] 2023-02-19 21:53
Yeah, it is a bug, I'll fix it.

The root cause of the bug that if there no folder with a given username it tries to re-create the user. I just forgot to put `--exist-ok` flag to the `createsuperuser` management command

**Comment by myrsk** [comment] 2023-02-20 05:36
> Yeah, it is a bug, I'll fix it.
> 
> 
> 
> The root cause of the bug that if there no folder with a given username it tries to re-create the user. I just forgot to put `--exist-ok` flag to the `createsuperuser` management command

Ah ok, thanks for the clarification. 

I do have an admin folder existing, although it is in s3, and my shelf is connected to s3, but it still tries to recreate. How does the bug and fix work in relation to s3? Thanks

**Comment by unmade** [comment] 2023-02-20 21:59
I've pushed a fix. You can try pull docker image with `0.1.0-alpha.12` tag
Please, let me know if it works for you!

**Closed** 2023-04-02 19:31 UTC
